# Server Port for accessing
server.port=8761

# Eureka Configuration for registration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Spring Security Credentials (Testing username)
spring.security.user.name=saleh
spring.security.user.password=scadfinal