# Application Name (for Eureka)
spring.application.name=product-service

# Server Port
server.port=8081

# Eureka Server with Authentication
eureka.client.serviceUrl.defaultZone=http://admin:admin@localhost:8761/eureka/

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console